[package]
name = "syn"
version = "0.11.11" # don't forget to update version in readme for breaking changes
authors = ["David Tolnay <dtolnay@gmail.com>"]
license = "MIT/Apache-2.0"
description = "Nom parser for Rust source code"
repository = "https://github.com/dtolnay/syn"
documentation = "https://dtolnay.github.io/syn/syn/"
categories = ["development-tools::procedural-macro-helpers"]
include = ["/Cargo.toml", "/src/**/*.rs", "/README.md", "/LICENSE-APACHE", "/LICENSE-MIT"]
publish = false # this branch contains breaking changes

[[example]]
name = "dump-ast"
path = "examples/dump-ast.rs"
required-features = ["extra-traits", "parsing", "printing", "full"]

[features]
default = ["parsing", "printing", "clone-impls"]
unstable = ["visit", "proc-macro2/unstable"]
full = []
parsing = ["quote"]
printing = ["quote"]
visit = []
visit_mut = []
fold = []
clone-impls = []
extra-traits = []
verbose-trace = []
all-features = []

[dependencies]
quote = { git = 'https://github.com/dtolnay/quote', optional = true }
proc-macro2 = "0.1"
unicode-xid = "0.1"

[dev-dependencies]
rayon = "0.9"
walkdir = "1.0.1"

[patch.crates-io]
proc-macro2 = { path = "../proc-macro2" }
